######################################################################
# Automatically generated by qmake (2.01a) Sat Apr 9 15:30:54 2011
######################################################################
QT+=sql
TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += dis.h
SOURCES += dis.cpp main.cpp
