######################################################################
# Automatically generated by qmake (2.01a) Tue Nov 30 08:11:49 2010
######################################################################
QT+=network
QT+=sql
TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += server.h
SOURCES += main.cpp server.cpp
