######################################################################
# Automatically generated by qmake (2.01a) Wed Mar 14 16:38:22 2012
######################################################################
QT+=sql
TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += server.h
SOURCES += main.cpp server.cpp
