######################################################################
# Automatically generated by qmake (2.01a) Mon Nov 29 22:00:27 2010
######################################################################
QT+=network
TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += client.h
SOURCES += client.cpp main.cpp
