######################################################################
# Automatically generated by qmake (2.01a) Mon Apr 18 23:38:06 2011
######################################################################
QT+=sql
TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += client.h
SOURCES += client.cpp main.cpp
